var FILM_LANDMARKS = [
{ name:"Mrs. Doubtfire House", county:"San Francisco", emoji:"🎬", lat:37.7939, lon:-122.4364, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Mrs._Doubtfire_house_San_Francisco.jpg/320px-Mrs._Doubtfire_house_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Mrs. Doubtfire (1993)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The iconic Victorian at 2640 Steiner St where Daniel Hillard disguised himself as a British nanny — every exterior home scene was filmed here.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The real address matches the movie address exactly. Fans still leave flowers and notes on the front steps.</span></div>" },
{ name:"The Painted Ladies", county:"San Francisco", emoji:"🎬", lat:37.7763, lon:-122.4328, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Painted_Ladies_San_Francisco_with_skyline.jpg/320px-Painted_Ladies_San_Francisco_with_skyline.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Full House (1987–1995)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>These seven Victorians on Alamo Square appeared in the Full House opening credits, with the Tanner family picnicking in the park as the skyline glittered behind them.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The actual Tanner house used for exterior shots is 1709 Broderick St — four blocks away from the Painted Ladies.</span></div>" },
{ name:"Palace of Fine Arts", county:"San Francisco", emoji:"🎬", lat:37.8029, lon:-122.4484, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Palace_of_Fine_Arts_San_Francisco.jpg/320px-Palace_of_Fine_Arts_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Rock (1996) / Vertigo (1958)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>In The Rock, Nicolas Cage and Sean Connery meet here in a tense handoff. Hitchcock filmed key Vertigo scenes in and around this rotunda.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Built as a temporary structure for the 1915 World's Fair out of plaster — San Franciscans refused to tear it down.</span></div>" },
{ name:"Lombard Street", county:"San Francisco", emoji:"🎬", lat:37.8021, lon:-122.4186, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Lombard_street_in_SF_4.jpg/320px-Lombard_street_in_SF_4.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Ant-Man (2015) / Bullitt (1968)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Crookedest Street in the World has anchored SF car chase sequences for decades. Bullitt's iconic chase wound through these streets; Ant-Man used it for a shrunken-down pursuit.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The speed limit is only 5 mph — making filmed chases here look far more dramatic than they were to shoot.</span></div>" },
{ name:"Alcatraz Island", county:"San Francisco", emoji:"🎬", lat:37.8270, lon:-122.4230, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Alcatraz_Island_as_seen_from_above.jpg/320px-Alcatraz_Island_as_seen_from_above.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Escape from Alcatraz (1979) / The Rock (1996)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Clint Eastwood's escape thriller was partially filmed on the actual island. The Rock used Alcatraz as its primary setting for the entire hostage crisis storyline.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Filming The Rock required nights on the island — crew members reported hearing unexplained sounds in the cellblock after dark.</span></div>" },
{ name:"Fort Point", county:"San Francisco", emoji:"🎬", lat:37.8103, lon:-122.4772, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Fort_Point_from_Golden_Gate_Bridge.jpg/320px-Fort_Point_from_Golden_Gate_Bridge.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Vertigo (1958) / Dawn of the Planet of the Apes (2014)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Hitchcock's most famous image: Scottie pulls Madeleine from the bay directly below the Golden Gate Bridge. Dawn of the Apes used it as a key ape territory boundary.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Bridge engineers wanted to demolish Fort Point. Strauss instead built a special arch over it — you can stand inside the fort and look straight up at the bridge.</span></div>" },
{ name:"Chinatown Gate", county:"San Francisco", emoji:"🎬", lat:37.7907, lon:-122.4056, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dragon_Gate_San_Francisco.jpg/320px-Dragon_Gate_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Big Trouble in Little China (1986)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Jack Burton drives his big rig through this gate at the start of his adventure into the supernatural underworld of SF's Chinatown in John Carpenter's cult classic.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>This Dragon Gate is the only authentic Chinatown ceremonial gate in the US with stone guardian lions flanking both sides.</span></div>" },
{ name:"Coit Tower", county:"San Francisco", emoji:"🎬", lat:37.8024, lon:-122.4058, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Coit_Tower%2C_SF.jpg/320px-Coit_Tower%2C_SF.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Enforcer (1976) / San Andreas (2015)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Coit Tower served as a dramatic backdrop for multiple Dirty Harry films. In San Andreas, Dwayne Johnson's helicopter rescue sequence sweeps past it as the city crumbles.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The tower's Depression-era murals caused a near-scandal in 1934 — officials tried to paint over the communist imagery before public outrage stopped them.</span></div>" },
{ name:"San Francisco City Hall", county:"San Francisco", emoji:"🎬", lat:37.7793, lon:-122.4193, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/San_Francisco_City_Hall_at_night.jpg/320px-San_Francisco_City_Hall_at_night.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Raiders of the Lost Ark (1981) / Milk (2008)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The grand rotunda doubled as the U.S. Capitol for Raiders of the Lost Ark. Gus Van Sant filmed Harvey Milk's political scenes here for the 2008 biopic.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The dome is the fifth largest in the world — three feet taller than the U.S. Capitol dome in Washington D.C.</span></div>" },
{ name:"555 California Street", county:"San Francisco", emoji:"🎬", lat:37.7922, lon:-122.4038, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/555_California_Street_2.jpg/320px-555_California_Street_2.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Towering Inferno (1974)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>This skyscraper represented the fictional Glass Tower in the disaster epic, with Steve McQueen and Paul Newman racing to save survivors from a 138-story inferno.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The film so terrified the public it changed high-rise fire safety codes nationwide. It was the tallest building in SF for nearly 50 years.</span></div>" },
{ name:"The Fairmont Hotel", county:"San Francisco", emoji:"🎬", lat:37.7925, lon:-122.4103, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Fairmont_Hotel_SF.jpg/320px-Fairmont_Hotel_SF.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Rock (1996) / Shang-Chi (2021)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Rock's villain holds his hostage crisis briefing in the Fairmont's ornate ballroom. Marvel's Shang-Chi filmed its opening SF action sequences around Nob Hill.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Fairmont is where the original United Nations Charter was drafted in 1945 — in the very ballroom used in The Rock.</span></div>" },
{ name:"Mission Dolores Park", county:"San Francisco", emoji:"🎬", lat:37.7596, lon:-122.4269, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Mission_Dolores_Basilica.jpg/320px-Mission_Dolores_Basilica.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Milk (2008)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Harvey Milk held his famous political rallies at Dolores Park — it became the symbolic heart of the Castro neighborhood's fight for equality in the film.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The park offers what cinematographers call the truest wide view of the SF skyline — it has appeared in dozens of films and TV shows.</span></div>" },
{ name:"Grace Cathedral", county:"San Francisco", emoji:"🎬", lat:37.7919, lon:-122.4128, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Grace_Cathedral_San_Francisco.jpg/320px-Grace_Cathedral_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Bullitt (1968)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Gothic towers of Grace Cathedral appear in several atmospheric sequences in Bullitt — director Peter Yates wanted the imposing stonework as a contrast to the raw action.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Grace Cathedral contains two labyrinths for walking meditation — one inside on the nave floor, and one outside in terrazzo stone.</span></div>" },
{ name:"Ferry Building", county:"San Francisco", emoji:"🎬", lat:37.7956, lon:-122.3935, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/San_Francisco_Ferry_Building.jpg/320px-San_Francisco_Ferry_Building.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Hulk (2003)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>In Ang Lee's Hulk, Bruce Banner's alter ego tears through the Embarcadero and battles military helicopters directly in front of the Ferry Building's clock tower.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Ferry Building's clock kept running through the catastrophic 1906 earthquake — it became a symbol of SF resilience and appeared on early postcards of the rebuilt city.</span></div>" },
{ name:"Kezar Stadium", county:"San Francisco", emoji:"🎬", lat:37.7670, lon:-122.4556, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Kezar_Stadium_Aerial.jpg/320px-Kezar_Stadium_Aerial.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Dirty Harry (1971)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The stadium's empty field at night is where the Scorpio killer forces Harry Callahan on a humiliating chase — culminating in the famous Do you feel lucky, punk? confrontation.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Kezar was the original home of the San Francisco 49ers from 1946 to 1970.</span></div>" },
{ name:"Musee Mecanique", county:"San Francisco", emoji:"🎬", lat:37.8095, lon:-122.4163, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Mus%C3%A9e_M%C3%A9canique_San_Francisco.jpg/320px-Mus%C3%A9e_M%C3%A9canique_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Princess Diaries (2001)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The antique penny arcade at Fisherman's Wharf is where Princess Mia has her first joyful moments in San Francisco before discovering her royal lineage.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Many of the 300+ mechanical arcade machines here are over 100 years old and still operate on quarters — one of the largest private antique arcade collections in the world.</span></div>" },
{ name:"Castro Theatre", county:"San Francisco", emoji:"🎬", lat:37.7620, lon:-122.4347, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Castro_Theatre_San_Francisco.jpg/320px-Castro_Theatre_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Milk (2008)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Castro Theatre was Harvey Milk's neighborhood cinema. Gus Van Sant filmed key scenes here capturing it as the cultural heart of the gay rights movement.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Castro Theatre has a custom-built pipe organ that rises from below the stage before every screening — a beloved tradition that continues today.</span></div>" },
{ name:"Twin Peaks", county:"San Francisco", emoji:"🎬", lat:37.7544, lon:-122.4477, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/San_Francisco_from_Twin_Peaks.jpg/320px-San_Francisco_from_Twin_Peaks.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Memoirs of an Invisible Man (1992)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Twin Peaks is the go-to location for sweeping city-overview shots. Chevy Chase's invisible protagonist uses the hilltop sightlines to orient himself while evading government agents.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Spanish explorers named these hills Los Pechos de la Chola. The name was quietly changed to Twin Peaks during the American period.</span></div>" },
{ name:"Cable Car Turnaround", county:"San Francisco", emoji:"🎬", lat:37.7845, lon:-122.4080, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/San_Francisco_Cable_Car_at_Powell_and_Market.jpg/320px-San_Francisco_Cable_Car_at_Powell_and_Market.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Princess Diaries (2001) / Venom (2018)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Powell Street cable car turnaround is one of the most filmed transit locations in the world. Princess Mia rides it in her transformation montage; Venom's chase sequences use the surrounding streets.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>These are the last manually operated cable cars in existence anywhere in the world. Tourists are invited to help push the car around the turntable.</span></div>" },
{ name:"St. Peter and Paul Church", county:"San Francisco", emoji:"🎬", lat:37.8016, lon:-122.4102, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Saints_Peter_and_Paul_Church_San_Francisco.jpg/320px-Saints_Peter_and_Paul_Church_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Sister Act (1992)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The North Beach church's soaring twin spires provided the setting for Whoopi Goldberg's choir scenes as Sister Mary Clarence transforms the parish choir into a gospel sensation.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Marilyn Monroe and Joe DiMaggio took their wedding photographs on these steps in 1954 — though they married at City Hall, the church would not perform the ceremony.</span></div>" },
{ name:"Lafayette Park SF", county:"San Francisco", emoji:"🎬", lat:37.7914, lon:-122.4277, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Lafayette_Park_San_Francisco.jpg/320px-Lafayette_Park_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Wedding Planner (2001)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>This hilltop park in Pacific Heights is where Jennifer Lopez and Matthew McConaughey meet by chance — the meet-cute scene that sets the entire film in motion.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Lafayette Park was the site of a 40-year legal battle after a squatter built a mansion in the middle of the public park in the 1880s and refused to leave.</span></div>" },
{ name:"Pier 7 San Francisco", county:"San Francisco", emoji:"🎬", lat:37.7994, lon:-122.3970, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Embarcadero_San_Francisco.jpg/320px-Embarcadero_San_Francisco.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Ant-Man and the Wasp (2018)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The longest wooden pier on the SF waterfront was used for chase and shrinking sequences — its straight lines made it ideal for the visual effects team.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Pier 7 is perfectly aligned with the Transamerica Pyramid when viewed from the Embarcadero — a sight line that appears in countless films and photographs of the city.</span></div>" },
{ name:"Bridges Restaurant Danville", county:"Contra Costa", emoji:"🎬", lat:37.8228, lon:-122.0004, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Bridges_restaurant_Danville_California.jpg/320px-Bridges_restaurant_Danville_California.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Mrs. Doubtfire (1993)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The film's most memorable sequence — Robin Williams races back and forth to the bathroom switching between Mrs. Doubtfire and Daniel Hillard for two different tables at the same restaurant.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The restaurant is still open today and looks remarkably similar to 1993. Staff will point out the exact tables used in the scene.</span></div>" },
{ name:"Orinda Theatre Film", county:"Contra Costa", emoji:"🎬", lat:37.8824, lon:-122.1831, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Orinda_Theatre.jpg/320px-Orinda_Theatre.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>13 Reasons Why (2017)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Orinda Theatre's stunning Art Deco exterior appears as a backdrop in Netflix's 13 Reasons Why, standing in for the small-town movie house central to the show's Northern California setting.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The neon tower was declared a historic landmark after a community campaign in the 1990s saved it from demolition.</span></div>" },
{ name:"Alameda Naval Air Station", county:"Alameda", emoji:"🎬", lat:37.7554, lon:-122.2285, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/USS_Potomac_Oakland.jpg/320px-USS_Potomac_Oakland.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Matrix Reloaded (2003)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Wachowskis filmed the legendary 14-minute freeway chase on a 1.5-mile fake highway built on the decommissioned base runways — one of the most expensive single action sequences ever filmed.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The crew spent 6 months and $40 million building the fake highway. The sequence required 300 stunt performers and took 3 months to film.</span></div>" },
{ name:"UC Berkeley Sather Gate", county:"Alameda", emoji:"🎬", lat:37.8721, lon:-122.2590, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Campanile_UC_Berkeley.jpg/320px-Campanile_UC_Berkeley.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Oppenheimer (2023) / The Graduate (1967)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Sather Gate is the iconic campus entrance seen in Oppenheimer's Berkeley scenes. Dustin Hoffman's Benjamin Braddock also walks through this gate in The Graduate.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The free speech movement protests of the 1960s centered on the plaza just outside this gate — some of the most consequential student demonstrations in American history.</span></div>" },
{ name:"Grand Lake Theatre Oakland", county:"Alameda", emoji:"🎬", lat:37.8115, lon:-122.2475, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Grand_Lake_Theatre_Oakland.jpg/320px-Grand_Lake_Theatre_Oakland.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Sorry to Bother You (2018)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Grand Lake Theatre's ornate facade appears in Boots Riley's surrealist Oakland satire, grounding the film's heightened reality in a recognizable East Bay landmark.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Grand Lake Theatre is famous for using its marquee to post political messages to the city — as well known for its commentary as for its films.</span></div>" },
{ name:"Marin Civic Center", county:"Marin", emoji:"🎬", lat:37.9984, lon:-122.5312, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Marin_County_Civic_Center_Aerial.jpg/320px-Marin_County_Civic_Center_Aerial.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Gattaca (1997) / THX 1138 (1971)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Frank Lloyd Wright's masterpiece served as the futuristic society headquarters in Gattaca — its sweeping arches needed almost no modification to read as a utopian sci-fi world.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>George Lucas used this building as his primary design reference for the city of Naboo in the Star Wars prequel trilogy.</span></div>" },
{ name:"Muir Woods", county:"Marin", emoji:"🎬", lat:37.8970, lon:-122.5811, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muir_Woods_National_Monument.jpg/320px-Muir_Woods_National_Monument.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Rise of the Planet of the Apes (2011)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Caesar and the liberated apes take refuge in Muir Woods' ancient redwood groves in the film's triumphant final act — the forest's cathedral-like scale made it the perfect sanctuary.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The redwoods here are between 500 and 1,200 years old. The tallest is 258 feet — taller than the Statue of Liberty from base to torch.</span></div>" },
{ name:"Point Reyes Lighthouse", county:"Marin", emoji:"🎬", lat:38.0037, lon:-123.0233, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Point_Reyes_Lighthouse_2016.jpg/320px-Point_Reyes_Lighthouse_2016.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Fog (1980)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>John Carpenter used the remote wind-battered Point Reyes Lighthouse as the primary setting — the keeper's isolation and coastal fog made it perfect for his atmospheric horror film.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>You must walk down 313 steps to reach the lighthouse. On windy days the National Park Service closes the stairs entirely.</span></div>" },
{ name:"Santa Cruz Beach Boardwalk", county:"Santa Cruz", emoji:"🎬", lat:36.9644, lon:-122.0189, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Santa_Cruz_Beach_Boardwalk_2012.jpg/320px-Santa_Cruz_Beach_Boardwalk_2012.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Lost Boys (1987) / Us (2019)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The Boardwalk's neon-lit carousel set the tone of The Lost Boys — it's where the teenage vampires hunt. Jordan Peele returned for the eerie funhouse sequences in Us.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Giant Dipper wooden roller coaster opened in 1924, is a National Historic Landmark, and was still running when The Lost Boys filmed here — and still runs today.</span></div>" },
{ name:"Potter Schoolhouse", county:"Sonoma", emoji:"🎬", lat:38.3452, lon:-122.9739, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Potter_Schoolhouse_Bodega.jpg/320px-Potter_Schoolhouse_Bodega.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Birds (1963)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Alfred Hitchcock chose this 1873 schoolhouse for the harrowing scene where children flee across an open field as seagulls dive-bomb them — one of the most iconic images in horror history.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>Hitchcock found the schoolhouse being used as a private residence. His crew artificially aged the building to look more weathered before filming.</span></div>" },
{ name:"Goat Rock Beach", county:"Sonoma", emoji:"🎬", lat:38.4461, lon:-123.1257, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Goat_Rock_Beach_Sonoma_County.jpg/320px-Goat_Rock_Beach_Sonoma_County.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>The Goonies (1985)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>The final scene of The Goonies — where the pirate ship One-Eyed Willy's vessel sails out to sea as the kids watch from the beach — was filmed here, doubling for the Oregon coast.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The production chose Goat Rock specifically for its dramatic rock formations, which gave the Oregon coastal feel without actually filming in Oregon.</span></div>" },
{ name:"Chateau Montelena", county:"Napa", emoji:"🎬", lat:38.5806, lon:-122.6015, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Chateau_Montelena.jpg/320px-Chateau_Montelena.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Bottle Shock (2008)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>This winery was the star of Bottle Shock — the film about the 1976 Paris Wine Tasting where California wines shocked the world by beating the French.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The real 1976 Judgment of Paris shocked the wine world. French judges refused to believe the results when a Chateau Montelena Chardonnay came out on top.</span></div>" },
{ name:"Hearst Castle", county:"San Luis Obispo", emoji:"🎬", lat:35.6852, lon:-121.1666, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Hearst_Castle_September_2013.jpg/320px-Hearst_Castle_September_2013.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Spartacus (1960) / Lady Gaga: G.U.Y. (2014)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Hearst Castle's Neptune Pool and Roman architecture appeared in Spartacus. Lady Gaga used the castle as the primary location for her elaborate G.U.Y. music video.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>The Roman Pool is lined entirely with real 22-karat gold Venetian glass tiles. The Neptune Pool's temple facade contains genuine ancient Roman columns shipped from Europe by Hearst.</span></div>" },
{ name:"George Lucas Hometown Modesto", county:"Stanislaus", emoji:"🎬", lat:37.6391, lon:-120.9969, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Modesto_Arch.jpg/320px-Modesto_Arch.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>American Graffiti (1973)</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>George Lucas based his breakthrough film entirely on his own teenage years cruising McHenry Avenue in Modesto. Every character, car, and scene draws from his specific Modesto memories.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>American Graffiti launched the careers of Richard Dreyfuss, Harrison Ford, and Ron Howard simultaneously. Its $775,000 budget returned $200 million, funding Lucas's next project: Star Wars.</span></div>" },
{ name:"Knights Ferry Covered Bridge", county:"Stanislaus", emoji:"🎬", lat:37.8256, lon:-120.6653, cat:"Movie & TV Film", photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Morgan_Territory_Regional_Preserve.jpg/320px-Morgan_Territory_Regional_Preserve.jpg", fact:"<div class='film-row'><span class='film-label'>🎬 Movie</span><span class='film-val'>Various Westerns and Period Productions</span></div><div class='film-row'><span class='film-label'>🎥 The Scene</span><span class='film-val'>Knights Ferry's covered bridge, 19th-century stone buildings, and wild river setting make it one of the most authentic Gold Rush-era film locations in California, used for westerns and period dramas.</span></div><div class='film-row'><span class='film-label'>⭐ Fun Fact</span><span class='film-val'>At 330 feet, this is the longest covered bridge west of the Mississippi River. It was designed by a West Point-trained engineer using techniques identical to New England covered bridges.</span></div>" }
];

var ALL_LANDMARKS = (function() {
  var seen = {};
  var out  = [];

  // Normalise any landmark object to our standard schema
  function norm(lm) {
    // coords: support both flat lat/lon and nested coords:{lat,lng}
    var lat = (lm.lat != null) ? lm.lat : (lm.coords ? lm.coords.lat : null);
    var lon = (lm.lon != null) ? lm.lon
            : (lm.coords ? (lm.coords.lon != null ? lm.coords.lon : lm.coords.lng) : null);

    // photo: support both 'photo' and 'image' fields
    var photo = lm.photo || lm.image || '';

    // fact: plain landmarks use 'fact'; film entries get structured 3-part card
    var fact = lm.fact || '';
    if (!fact && lm.media) {
      fact = '<div class="film-row"><span class="film-label">🎬 Movie</span><span class="film-val">' + (lm.media || '') + '</span></div>'
           + '<div class="film-row"><span class="film-label">🎥 The Scene</span><span class="film-val">' + (lm.scene || lm.history || '') + '</span></div>'
           + '<div class="film-row"><span class="film-label">⭐ Fun Fact</span><span class="film-val">' + (lm.fun_fact || '') + '</span></div>';
    }

    // cat: film entries with no cat get assigned one
    var cat = lm.cat || '';
    if (!cat && lm.media) cat = 'Movie & TV Film';

    return {
      name:   lm.name   || '',
      county: lm.county || '',
      emoji:  lm.emoji  || '📍',
      lat:    lat,
      lon:    lon,
      cat:    cat,
      photo:  photo,
      fact:   fact
    };
  }

  // Merge an array of raw landmark objects
  function merge(arr) {
    if (!arr || !arr.length) return;
    for (var i = 0; i < arr.length; i++) {
      var n   = norm(arr[i]);
      if (!n.lat || !n.lon || !n.name) continue;   // skip invalid
      var key = n.name.toLowerCase().trim();
      if (seen[key]) continue;                      // deduplicate
      seen[key] = true;
      out.push(n);
    }
  }

  // Pull from each file — graceful if a file didn't load
  if (typeof LANDMARKS             !== 'undefined') merge(LANDMARKS);
  if (typeof LANDMARKS_SOUTH       !== 'undefined') merge(LANDMARKS_SOUTH);
  if (typeof LANDMARKS_TOPUP       !== 'undefined') merge(LANDMARKS_TOPUP);
  if (typeof LANDMARKS_VALLEY       !== 'undefined') merge(LANDMARKS_VALLEY);
